name: app

type: php:8.1

dependencies:
    php:
        composer/composer: "^2"

runtime:
    extensions:
        - apcu
        - ctype
        - iconv
        - mbstring
        - pdo_pgsql
        - sodium
        - xsl

variables:
    php:
        opcache.preload: /app/config/preload.php
build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var": { source: local, source_path: var }

relationships:
    database: "database:postgresql"

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash
        
        symfony-build

    deploy: |
        set -x -e

        symfony-deploy

crons:
    refresh-scrabble:
        spec: '30 * * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = "main" ]; then
                croncape symfony console app:scrabble:regenerate
            fi